### ISSUE TITLE
Add a linter/compiler on the CI

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-operations#3]
A linter/compiler like https://github.com/uber/prototool could be added as a GitHub Actions to check that the files compile and are well formatted.
Currently our formatting is poor, for example the indentation is not consistent.

**Comment by ionut-arm** [comment]
>  asym_sign.proto:1:1:File option "go_package" is required.
> asym_sign.proto:1:1:File option "java_multiple_files" is required.
> asym_sign.proto:1:1:File option "java_outer_classname" is required.
> asym_sign.proto:1:1:File option "java_package" is required.
> asym_sign.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> asym_sign.proto:17:1:C-Style comments are not allowed.
> asym_verify.proto:1:1:File option "go_package" is required.
> asym_verify.proto:1:1:File option "java_multiple_files" is required.
> asym_verify.proto:1:1:File option "java_outer_classname" is required.
> asym_verify.proto:1:1:File option "java_package" is required.
> asym_verify.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> asym_verify.proto:17:1:C-Style comments are not allowed.
> create_key.proto:1:1:File option "go_package" is required.
> create_key.proto:1:1:File option "java_multiple_files" is required.
> create_key.proto:1:1:File option "java_outer_classname" is required.
> create_key.proto:1:1:File option "java_package" is required.
> create_key.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> create_key.proto:17:1:C-Style comments are not allowed.
> destroy_key.proto:1:1:File option "go_package" is required.
> destroy_key.proto:1:1:File option "java_multiple_files" is required.
> destroy_key.proto:1:1:File option "java_outer_classname" is required.
> destroy_key.proto:1:1:File option "java_package" is required.
> destroy_key.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> destroy_key.proto:17:1:C-Style comments are not allowed.
> export_public_key.proto:1:1:File option "go_package" is required.
> export_public_key.proto:1:1:File option "java_multiple_files" is required.
> export_public_key.proto:1:1:File option "java_outer_classname" is required.
> export_public_key.proto:1:1:File option "java_package" is required.
> export_public_key.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> export_public_key.proto:17:1:C-Style comments are not allowed.
> import_key.proto:1:1:File option "go_package" is required.
> import_key.proto:1:1:File option "java_multiple_files" is required.
> import_key.proto:1:1:File option "java_outer_classname" is required.
> import_key.proto:1:1:File option "java_package" is required.
> import_key.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> import_key.proto:17:1:C-Style comments are not allowed.
> key_attributes.proto:1:1:File option "go_package" is required.
> key_attributes.proto:1:1:File option "java_multiple_files" is required.
> key_attributes.proto:1:1:File option "java_outer_classname" is required.
> key_attributes.proto:1:1:File option "java_package" is required.
> key_attributes.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> key_attributes.proto:17:1:C-Style comments are not allowed.
> key_attributes.proto:22:4:Field name "Volatile" must be UPPER_SNAKE_CASE.
> key_attributes.proto:22:4:Enum field "Volatile" is expected to have the prefix "KEY_LIFETIME_".
> key_attributes.proto:22:4:Zero value enum field "Volatile" is expected to have the name "KEY_LIFETIME_INVALID".
> key_attributes.proto:23:4:Field name "Persistent" must be UPPER_SNAKE_CASE.
> key_attributes.proto:23:4:Enum field "Persistent" is expected to have the prefix "KEY_LIFETIME_".
> key_attributes.proto:27:4:Field name "HMAC_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:27:4:Enum field "HMAC_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:27:4:Zero value enum field "HMAC_Key" is expected to have the name "KEY_TYPE_INVALID".
> key_attributes.proto:28:4:Field name "Derivation_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:28:4:Enum field "Derivation_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:29:4:Field name "AES_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:29:4:Enum field "AES_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:30:4:Field name "DES_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:30:4:Enum field "DES_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:31:4:Field name "Camellia_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:31:4:Enum field "Camellia_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:32:4:Field name "ARC4_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:32:4:Enum field "ARC4_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:33:4:Field name "RSA_Public_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:33:4:Enum field "RSA_Public_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:34:4:Field name "RSA_Keypair" must be UPPER_SNAKE_CASE.
> key_attributes.proto:34:4:Enum field "RSA_Keypair" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:35:4:Field name "DSA_Public_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:35:4:Enum field "DSA_Public_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:36:4:Field name "DSA_Keypair" must be UPPER_SNAKE_CASE.
> key_attributes.proto:36:4:Enum field "DSA_Keypair" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:37:4:Field name "ECC_Public_Key" must be UPPER_SNAKE_CASE.
> key_attributes.proto:37:4:Enum field "ECC_Public_Key" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:38:4:Field name "ECC_Keypair" must be UPPER_SNAKE_CASE.
> key_attributes.proto:38:4:Enum field "ECC_Keypair" is expected to have the prefix "KEY_TYPE_".
> key_attributes.proto:42:4:Field name "No_Ecc_Curve" must be UPPER_SNAKE_CASE.
> key_attributes.proto:42:4:Enum field "No_Ecc_Curve" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:42:4:Zero value enum field "No_Ecc_Curve" is expected to have the name "ECC_CURVE_INVALID".
> key_attributes.proto:43:4:Enum field "SECT163K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:44:4:Enum field "SECT163R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:45:4:Enum field "SECT163R2" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:46:4:Enum field "SECT193R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:47:4:Enum field "SECT193R2" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:48:4:Enum field "SECT233K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:49:4:Enum field "SECT233R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:50:4:Enum field "SECT239K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:51:4:Enum field "SECT283K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:52:4:Enum field "SECT283R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:53:4:Enum field "SECT409K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:54:4:Enum field "SECT409R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:55:4:Enum field "SECT571K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:56:4:Enum field "SECT571R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:57:4:Enum field "SECP160K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:58:4:Enum field "SECP160R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:59:4:Enum field "SECP160R2" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:60:4:Enum field "SECP192K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:61:4:Enum field "SECP192R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:62:4:Enum field "SECP224K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:63:4:Enum field "SECP224R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:64:4:Enum field "SECP256K1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:65:4:Enum field "SECP256R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:66:4:Enum field "SECP384R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:67:4:Enum field "SECP521R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:68:4:Enum field "BRAINPOOL_P256R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:69:4:Enum field "BRAINPOOL_P384R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:70:4:Enum field "BRAINPOOL_P512R1" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:71:4:Enum field "CURVE25519" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:72:4:Enum field "CURVE448" is expected to have the prefix "ECC_CURVE_".
> key_attributes.proto:76:4:Field name "No_Hash_Algorithm" must be UPPER_SNAKE_CASE.
> key_attributes.proto:76:4:Enum field "No_Hash_Algorithm" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:76:4:Zero value enum field "No_Hash_Algorithm" is expected to have the name "HASH_ALGORITHM_INVALID".
> key_attributes.proto:77:4:Enum field "MD2" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:78:4:Enum field "MD4" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:79:4:Enum field "MD5" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:80:4:Enum field "RIPEMD160" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:81:4:Enum field "SHA_1" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:82:4:Enum field "SHA_224" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:83:4:Enum field "SHA_256" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:84:4:Enum field "SHA_384" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:85:4:Enum field "SHA_512" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:86:4:Enum field "SHA_512_224" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:87:4:Enum field "SHA_512_256" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:88:4:Enum field "SHA3_224" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:89:4:Enum field "SHA3_256" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:90:4:Enum field "SHA3_384" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:91:4:Enum field "SHA3_512" is expected to have the prefix "HASH_ALGORITHM_".
> key_attributes.proto:95:4:Enum field "ARC4" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:95:4:Zero value enum field "ARC4" is expected to have the name "CIPHER_ALGORITHM_INVALID".
> key_attributes.proto:96:4:Enum field "CTR" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:97:4:Enum field "CFB" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:98:4:Enum field "OFB" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:99:4:Enum field "XTS" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:100:4:Field name "CBC_No_Padding" must be UPPER_SNAKE_CASE.
> key_attributes.proto:100:4:Enum field "CBC_No_Padding" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:101:4:Enum field "CBC_PKCS7" is expected to have the prefix "CIPHER_ALGORITHM_".
> key_attributes.proto:105:4:Field name "RSA_PKCS1V15_Crypt" must be UPPER_SNAKE_CASE.
> key_attributes.proto:105:4:Enum field "RSA_PKCS1V15_Crypt" is expected to have the prefix "ASYMMETRIC_ENCRYPTION_ALGORITHM_".
> key_attributes.proto:105:4:Zero value enum field "RSA_PKCS1V15_Crypt" is expected to have the name "ASYMMETRIC_ENCRYPTION_ALGORITHM_INVALID".
> key_attributes.proto:106:4:Enum field "RSA_OAEP" is expected to have the prefix "ASYMMETRIC_ENCRYPTION_ALGORITHM_".
> key_attributes.proto:115:4:Enum field "HMAC" is expected to have the prefix "MAC_ALGORITHM_".
> key_attributes.proto:115:4:Zero value enum field "HMAC" is expected to have the name "MAC_ALGORITHM_INVALID".
> key_attributes.proto:116:4:Enum field "CBC_MAC" is expected to have the prefix "MAC_ALGORITHM_".
> key_attributes.proto:117:4:Enum field "CMAC" is expected to have the prefix "MAC_ALGORITHM_".
> key_attributes.proto:118:4:Enum field "GMAC" is expected to have the prefix "MAC_ALGORITHM_".
> key_attributes.proto:128:4:Enum field "CCM" is expected to have the prefix "AEAD_ALGORITHM_".
> key_attributes.proto:128:4:Zero value enum field "CCM" is expected to have the name "AEAD_ALGORITHM_INVALID".
> key_attributes.proto:129:4:Enum field "GCM" is expected to have the prefix "AEAD_ALGORITHM_".
> key_attributes.proto:138:4:Field name "RSA_PKCS1V15_Sign" must be UPPER_SNAKE_CASE.
> key_attributes.proto:138:4:Enum field "RSA_PKCS1V15_Sign" is expected to have the prefix "SIGN_ALGORITHM_".
> key_attributes.proto:138:4:Zero value enum field "RSA_PKCS1V15_Sign" is expected to have the name "SIGN_ALGORITHM_INVALID".
> key_attributes.proto:139:4:Enum field "RSA_PSS" is expected to have the prefix "SIGN_ALGORITHM_".
> key_attributes.proto:140:4:Enum field "DSA" is expected to have the prefix "SIGN_ALGORITHM_".
> key_attributes.proto:141:4:Field name "Deterministic_DSA" must be UPPER_SNAKE_CASE.
> key_attributes.proto:141:4:Enum field "Deterministic_DSA" is expected to have the prefix "SIGN_ALGORITHM_".
> key_attributes.proto:142:4:Enum field "ECDSA" is expected to have the prefix "SIGN_ALGORITHM_".
> key_attributes.proto:143:4:Field name "Deterministic_ECDSA" must be UPPER_SNAKE_CASE.
> key_attributes.proto:143:4:Enum field "Deterministic_ECDSA" is expected to have the prefix "SIGN_ALGORITHM_".
> key_attributes.proto:152:4:Enum field "HKDF" is expected to have the prefix "KEY_DERIVATION_FUNCTION_".
> key_attributes.proto:152:4:Zero value enum field "HKDF" is expected to have the name "KEY_DERIVATION_FUNCTION_INVALID".
> key_attributes.proto:153:4:Enum field "TLS12_PRF" is expected to have the prefix "KEY_DERIVATION_FUNCTION_".
> key_attributes.proto:154:4:Field name "TLS12_PSK_To_MS" must be UPPER_SNAKE_CASE.
> key_attributes.proto:154:4:Enum field "TLS12_PSK_To_MS" is expected to have the prefix "KEY_DERIVATION_FUNCTION_".
> key_attributes.proto:155:4:Field name "Select_Raw" must be UPPER_SNAKE_CASE.
> key_attributes.proto:155:4:Enum field "Select_Raw" is expected to have the prefix "KEY_DERIVATION_FUNCTION_".
> key_attributes.proto:164:4:Enum field "FFDH" is expected to have the prefix "KEY_AGREEMENT_ALGORITHM_".
> key_attributes.proto:164:4:Zero value enum field "FFDH" is expected to have the name "KEY_AGREEMENT_ALGORITHM_INVALID".
> key_attributes.proto:165:4:Enum field "ECDH" is expected to have the prefix "KEY_AGREEMENT_ALGORITHM_".
> list_opcodes.proto:1:1:File option "go_package" is required.
> list_opcodes.proto:1:1:File option "java_multiple_files" is required.
> list_opcodes.proto:1:1:File option "java_outer_classname" is required.
> list_opcodes.proto:1:1:File option "java_package" is required.
> list_opcodes.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> list_opcodes.proto:17:1:C-Style comments are not allowed.
> list_providers.proto:1:1:File option "go_package" is required.
> list_providers.proto:1:1:File option "java_multiple_files" is required.
> list_providers.proto:1:1:File option "java_outer_classname" is required.
> list_providers.proto:1:1:File option "java_package" is required.
> list_providers.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> list_providers.proto:17:2:C-Style comments are not allowed.
> ping.proto:1:1:File option "go_package" is required.
> ping.proto:1:1:File option "java_multiple_files" is required.
> ping.proto:1:1:File option "java_outer_classname" is required.
> ping.proto:1:1:File option "java_package" is required.
> ping.proto:1:1:Multiple packages in directory: asym_sign, asym_verify, create_key, destroy_key, export_public_key, import_key, key_attributes, list_opcodes, list_providers, ping.
> ping.proto:17:1:C-Style comments are not allowed.

We're gonna have a baaaaaad time when we'll want to fix all the linting issues
